### ISSUE TITLE
有没有64位可以用的？

### ISSUE THREAD

**Issue by Layczm** [charminghiker/dll_tool#1]
最近需求通过调用dll读卡操作，

**Comment by charminghiker** [comment]
64位机器没有特别要求，使用这个32位的也兼容。
如果有特别要求，node编译时使用64位node即可。

**Comment by charminghiker** [comment]
64位机器没有特别要求，使用这个32位的也兼容。
如果有特别要求，node编译时使用64位node即可。

> 最近需求通过调用dll读卡操作，

**Comment by Layczm** [comment]
PS D:\Desktop\新桌面\dll_tool-master> node-gyp install --dist-url=https://npm.taobao.org/mirrors/node
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.13.0 | win32 | x64
gyp http GET https://npm.taobao.org/mirrors/node/v8.13.0/node-v8.13.0-headers.tar.gz
gyp http 200 https://npm.taobao.org/mirrors/node/v8.13.0/node-v8.13.0-headers.tar.gz
gyp http GET https://npm.taobao.org/mirrors/node/v8.13.0/SHASUMS256.txt
gyp http GET https://npm.taobao.org/mirrors/node/v8.13.0/win-x64/node.lib
gyp http GET https://npm.taobao.org/mirrors/node/v8.13.0/win-x86/node.lib
gyp http 200 https://npm.taobao.org/mirrors/node/v8.13.0/SHASUMS256.txt
gyp http 200 https://npm.taobao.org/mirrors/node/v8.13.0/win-x86/node.lib
gyp http 200 https://npm.taobao.org/mirrors/node/v8.13.0/win-x64/node.lib
8.13.0
gyp info ok
PS D:\Desktop\新桌面\dll_tool-master> npm install

> ref-napi@3.0.3 install D:\Desktop\新桌面\dll_tool-master\node_modules\ref-napi
> node-gyp-build


D:\Desktop\新桌面\dll_tool-master\node_modules\ref-napi>if not defined npm_config_node_gyp (node "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 941, in _GenerateProject
    return _GenerateMSBuildProject(project, options, version, generator_flags)
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 3368, in _GenerateMSBuildProject
    easy_xml.WriteXmlIfChanged(content, project.path, pretty=True, win32=True)
  File "D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 122, in WriteXmlIfChanged
    xml_string = xml_string.decode(default_encoding).encode(encoding)
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 3132-3133: illegal multibyte sequence
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\dev\nvm\v8.13.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\dev\\nodejs\\node.exe" "D:\\dev\\nvm\\v8.13.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Desktop\新桌面\dll_tool-master\node_modules\ref-napi
gyp ERR! node -v v8.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN dll_tool@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref-napi@3.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref-napi@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\10215\AppData\Roaming\npm-cache\_logs\2022-01-06T10_15_53_191Z-debug.log
运行不起来，  5 - 5 
 而且这个可以在另一个项目中引入使用么？怎么引用？ ？

**Comment by charminghiker** [comment]
第一步npm install -g windows-build-tools执行了么
引用就得加express，起个服务，暴露个接口出来

**Comment by Layczm** [comment]
但是我们这边产品的话是想把卡放在读卡器上，然后点击界面的按钮读卡， 在界面上显示卡号，不会说在起另一个服务的 5 - 5
